[values]
team_score = 0
adversaire_score = 0

[url]
match = "https://docs.google.com/spreadsheets/d/1F0NI-6_oi_geBDIJge9b6FXipMUyDw3XR90rHDALCx8/edit"
history = "https://docs.google.com/spreadsheets/d/14vdIL4MwuOHDxsY6bb3rfkjbbVd4iXw2ZcIwG8rNBfo/edit"

[pages]
first = "En Cours"
second = "Données des Match"
third = "Analyse des Match (Incomplet)"
fourth = "Data Science (Incomplete)"

[teams]
first = "Nantes"
second = "Pujols"
third = "Trentels"
fourth = "Begles"
fifth = "Clairac"
sixth = "Agenais"
seventh = "Villeneuve-de-Rivière"
eight = "Saint-Pois"
tenth = "Adversaire"

[actions]
first = "Plaquage"
second = "Plaquage (en but)"
third = "Coup de pied"
fourth = "Essai"
fifth = "Transformation"
sixth = "Drop"
seventh = "Sortie de balle"
eight = "Pénalité/Faute"
ninth = "Pénalité (Carte Jaune)"
tenth = "Pénalité (Carte Rouge)"

[zones]
first = "{your_team} 40m"
second = "Adversaire 40m"
third = "Milieu"

[places]
first = "Domicile "
second = "Extérieur"

[winner]
first = "{your_team}"
second = "Adversaire"

[column_names]
location = "Lieu du match"
opponent = "Nom de l'adversaire"
time = "Temps"
half = "Mi-Temps"
set = "Série"
actor = "Evénement"
action = "Action"
area = "Zone"
team_score = "Équipe Score"
opponent_score = "Adversaire Score"

[html]
string_one = """<!DOCTYPE html>
<html>
  <head>
    <title>Center Text</title>
    <style>
      body {
        height: 100vh;
      }
      .container {
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
      }
      p {
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <p>This is a centered paragraph of text.</p>
    </div>
  </body>
</html>
"""